{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "pagespeed-exporter.fullname" . }}
  labels:
  {{- include "pagespeed-exporter.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Values.cronjob.image.name }}
              image: "{{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag | default "latest" }}"
              imagePullPolicy: {{ .Values.cronjob.image.pullPolicy }}
              args:
                - -sSv
                - -H
                - "X-Prometheus-Scrape-Timeout-Seconds: {{ .Values.cronjob.scrapeTimeoutSeconds }}"
                - "http://{{ include "pagespeed-exporter.fullname" . }}:{{ .Values.service.port }}/probe?target={{- join "&target=" .Values.exporter.targets }}"
          restartPolicy: OnFailure
{{- end }}